### ISSUE TITLE
其他输入框配置无法生效

### ISSUE THREAD

**Issue by songshijun007** [hiouttime/dujiaoka#5]
作者您好，我按照提示 填写 qq_account=QQ账号=true

但是商品详情页没有新增输入框，这是什么原因啊

**Comment by huiypay** [comment]
应该是作者前端模版还未适配，建议用官方稳定版本的，此版本未完全测试

**Comment by songshijun007** [comment]
> 应该是作者前端模版还未适配，建议用官方稳定版本的，此版本未完全测试

谢老哥回复，安装了官方稳定版本也不行，我不知道是不是我操作有问题，检查了一边安装教程没发现问题啊，老哥你那边其他输入框配置可以生效么

**Comment by MushuScript** [comment]
我也是设置无效 但是我看别人的设置有效 https://www.vsshop.cc/buy/1 它的都可以

**Comment by LyceumHewun** [comment]
看了代码，人工处理方式才会有显示新增的输入框

**Comment by OwO996** [comment]
合并下新版 pr，只升级框架试试。

**Comment by hiouttime** [comment]
此问题可能因你商品类型为“自动发货”，这种情况下不会显示自定义输入框；
在新版本中，完全更新了回调服务器部分，你现在可以完整使用此功能。
